# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authoer',
            new_name='author',
        ),
    ]
